set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR ARM)

set(ARM_TOOLCHAIN_VERSION "10.3-2021.10")
set(ARM_TOOLCHAIN_TRIPPLE "arm-none-eabi")
set(ARM_TOOLCHAIN_COMPILER "gcc")

set(PICO_GCC_TRIPLE "${ARM_TOOLCHAIN_TRIPPLE}")
set(PICO_TOOLCHAIN_PATH "${CMAKE_CURRENT_LIST_DIR}/${ARM_TOOLCHAIN_COMPILER}-${ARM_TOOLCHAIN_TRIPPLE}-${ARM_TOOLCHAIN_VERSION}")